services:
  - type: web
    name: checkoutflow
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: checkoutflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: checkoutflow-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: checkoutflow-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: checkoutflow-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: checkoutflow-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: SUPERVISOR_PHP_USER
        value: root

databases:
  - name: checkoutflow-db
    plan: free
    databaseName: checkoutflow
    user: checkoutflow
